### ISSUE TITLE
Upgrade to embedded-hal 1.0.0-rc.1

### ISSUE THREAD

**Issue by clintfred** [TeyKey1/pca9535#2]
Thanks for your crate!

It look like the [embedded-hal 1.0 release is scheduled for 12/28/2023](https://github.com/rust-embedded/embedded-hal/issues/177#issuecomment-1821860952) and the rc.1 release should have the same API unless something goes off the rails.

Is there any work that needs to be done to upgrade?

**Comment by TeyKey1** [comment]
Hi @clintfred 

Thanks for letting me know about the future release of v1.0. Looks like it's really happening soon 😄 
I think there will be some small changes needed to pca9535 lib, but it should not be too drastic as far as I saw. We removed the IO-Pin trait in #1 which I'd like to get back in. But looks like this is not in 1.0 so it can be skipped for now.

I might need to make a few adjustments to the hardware testing, but rppal seems to support v1.0 rc2 already, so I only might need to patch shared-bus to v1.0 rc2 for now.

In case you need pca9535 to support v1.0 rc2 I can create a release candidate for you, otherwise I plan to release v2.0.0 of pca9535 once v1.0 of embedded-hal is released.

**Comment by clintfred** [comment]
Thank you for your response. I can wait for the 2.0 release; no worries.

FYI: I am using your crate with [linux-embedded-hal](https://github.com/rust-embedded/linux-embedded-hal).

If you need any support or feedback, I will try to help, just lmk.

**Comment by TeyKey1** [comment]
Ok, so I will wait for the official release. The update is now merged into master.

I'm always happy for any feedback regarding the library usage. In case there's something that is hard to achieve or does not work.

It's always nice to have people using the library in combination with other hardware and providing feedback in case anything does not work correctly. I myself only use it in combination with rppal on a Raspberry Pi 4 which is also used for the hardware based tests in this lib.
